name: Build and deploy

on:
  workflow_dispatch:
    inputs:
        imageVersion:
          description: 'Docker Image Version (x.x.x)'     
          required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: set env 'WS_NAME'
      run: echo ::set-env name=WS_NAME::nager-date
    - uses: actions/checkout@v2
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
     - name: Change LicenseKey
       if: github.event_name != 'pull_request'
       working-directory: ./src
       run: |
         sed -i 's/Thank you for supporting open source projects/${{secrets.LICENSE_KEY}}/g' Nager.Date/DateSystem.cs
         sed -i 's/Thank you for supporting open source projects/${{secrets.LICENSE_KEY}}/g' Nager.Date.UnitTest/AssemblyInitialize.cs
    - name: Restore dependencies
      working-directory: ./src
      run: dotnet restore
    - name: Test
      working-directory: ./src
      run: |
        dotnet test --configuration Release --no-restore --no-build --verbosity normal
    - name: Build Docker image
      uses: docker/build-push-action@v1.1.1
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_REGISTRY }}
        tags: ${{ env.IMAGE_PREFIX }}${{ github.event.inputs.imageVersion }}
